// Payloads copied verbatim from a dev backend (`alice_shop`), so a parse test
// fails when the contract moves rather than when somebody's guess about it does.

const meJson = <String, dynamic>{
  'id': 'acc_88sxn2txxspd4',
  'email': 'alice@shopnexus.test',
  'email_verified': true,
  'phone': null,
  'username': 'alice_shop',
  'role': 'user',
  'status': 'active',
  'has_password': true,
  'identity_verified': false,
  'profile': {
    'name': "Alice's Corner",
    'description': 'Pre-loved fashion and small home things.',
    'gender': null,
    'date_of_birth': null,
    'avatar': null,
    'country': 'VN',
    'locale': 'vi-VN',
    'timezone': 'Asia/Ho_Chi_Minh',
    'created_at': '2026-08-05T02:34:22.408272Z',
  },
  'created_at': '2026-08-05T02:34:22.408272Z',
};

const contactJson = <String, dynamic>{
  'id': 'ctc_ben6dg1c315mz',
  'full_name': "Alice's Corner",
  'phone': '+84900000001',
  'phone_verified': true,
  'address_type': 'home',
  'is_default_delivery': true,
  'is_default_pickup': true,
  'country': 'VN',
  'province_code': '31',
  'province_name': 'Hai Phong',
  'district_code': null,
  'district_name': null,
  'ward_code': '11365',
  'ward_name': 'May To',
  'postal_code': null,
  'address': 'May To, Hai Phong',
  'address_detail': null,
  'latitude': 20.874824027527453,
  'longitude': 106.66524643065901,
  'created_at': '2026-08-05T02:34:22.408272Z',
};

const orderItemJson = <String, dynamic>{
  'id': 'itm_fa1kdfqze7egn',
  'order_id': 'ord_2ybcv39246zn7',
  'listing_id': 'lst_a60p5qh3t6ry4',
  'variant_id': 'vrn_8vw1sy73ddpkc',
  'seller_id': 'acc_48gmxxfhd8ta3',
  'quantity': 2,
  'currency': 'VND',
  'total_amount': 98000,
  'transport_option': 'standard-delivery',
  'payment_session_id': 'pay_01bp1w1e0bg97',
  'cancelled_at': null,
  'created_at': '2026-08-05T02:47:11.309399Z',
};

const orderJson = <String, dynamic>{
  'id': 'ord_2ybcv39246zn7',
  'draft_id': 'drf_9s9npa0zabx7n',
  'offer_id': null,
  'buyer': {'id': 'acc_88sxn2txxspd4', 'name': "Alice's Corner"},
  'seller': {'id': 'acc_48gmxxfhd8ta3', 'name': 'Bob Electronics'},
  'address': {
    'full_name': "Alice's Corner",
    'phone': '+84900000001',
    'country': 'VN',
    'province_code': '31',
    'ward_code': '11365',
  },
  'pickup_address': {
    'full_name': 'Bob Electronics',
    'phone': '+84900000002',
    'country': 'VN',
    'province_code': '79',
    'ward_code': '26734',
  },
  'items': [orderItemJson],
  'state': 'open',
  'total': 98000,
  'currency': 'VND',
  'transport': {
    'id': 'trp_ep6bh2cqjsxy3',
    'option': 'standard-delivery',
    'status': 'pending',
    'fee': 15000,
    'created_at': '2026-08-05T02:47:38.200063Z',
  },
  'received_at': null,
  'receipt_attachments': <Map<String, dynamic>>[],
  'payout_deadline_at': null,
  'payout_released_at': null,
  'created_at': '2026-08-05T02:47:38.20111Z',
  'completed_at': null,
  'cancelled_at': null,
};

const notificationJson = <String, dynamic>{
  'category': 'order',
  'title': 'Order placed',
  'payload': {'order_id': 'ord_2ybcv39246zn7'},
  'read_at': null,
  'created_at': '2026-08-05T02:47:38.213999Z',
};

const listingJson = <String, dynamic>{
  'id': 'lst_a60p5qh3t6ry4',
  'slug': 'ke-ong-dung-dua-muong',
  'name': 'Kệ ống đựng đũa muỗng',
  'status': 'active',
  'condition': 'new',
  'price_mode': 'fixed',
  'currency': 'VND',
  'price': 49000,
  'sold': 0,
  'cover': {
    'id': 'res_cnzz61t6cr7pf',
    'provider': 'minio',
    'object_key': 'listings/cover.jpg',
    'mime': 'image/jpeg',
    'size': 12345,
    'url': 'https://cdn.example/cover.jpg',
  },
  'rating': 0,
  'review_count': 0,
  'category_id': 'cat_b68877mkawpab',
  'seller': {'id': 'acc_48gmxxfhd8ta3', 'name': 'Bob Electronics'},
  'favorited': false,
  'deleted_at': null,
  'created_at': '2026-08-02T04:55:15.318908Z',
};
